name: Two-Day Suitcase
url: http://twodaysuitcase.com
markdown: redcarpet
highlighter: null
timezone: America/Chicago
exclude: [Gemfile, Gemfile.lock]
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
