name: Two-Day Suitcase
url: http://twodaysuitcase.com
future: true
markdown: redcarpet
highlighter: rouge
timezone: America/Chicago
exclude: [Gemfile, Gemfile.lock, run_local.sh]
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
